.github/workflows/maven-deploy.yml, duo-client/pom.xml
https://github.com/AaronAtDuo/duo_client_java/actions/runs/360234469 shows it getting to the point where it fails validation due to my fake key
=> Pom changes and the github workflow for deploying to Maven

README.md
Realized we forgot to update the README when we published this to Maven.
=> List Maven information in readme

duo-client/pom.xml, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-client/src/test/java/com/duosecurity/client/HttpRateLimitRetryTest.java
code changes as necessary for the okhttp changes
=> Bump okhttp and guava dependency versions

duo-client/pom.xml, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-example-admin/pom.xml, pom.xml
=> Version 0.4.0 bump

README.md, duo-client/pom.xml, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-example-admin/pom.xml, pom.xml
=> Update README references to 0.4.0 and start 0.4.1 snapshot

duo-client/src/main/java/com/duosecurity/client/Http.java, duo-client/src/test/java/com/duosecurity/client/HttpCanonRequestTest.java, duo-client/src/test/java/com/duosecurity/client/HttpRateLimitRetryTest.java, duo-client/src/test/java/com/duosecurity/client/HttpSignHMACTest.java, duo-example-admin/src/main/java/com/duosecurity/example/DuoAdmin.java, duo-example-admin/src/main/java/com/duosecurity/example/DuoAuthLogsV2.java
Convert tests to use it and do some minor cleanup to construction
=> Introduce Builder for the Http class

duo-client/src/main/java/com/duosecurity/client/Http.java, duo-client/src/main/java/com/duosecurity/client/Util.java
To bring this in line with our other clients that do certificate pinning.
=> Add certificate pinning with support for custom certificates

duo-client/pom.xml, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-example-admin/pom.xml, pom.xml
In preparation for a Maven release
=> Version bump to 0.5.0

duo-client/src/main/java/com/duosecurity/client/Accounts.java, duo-client/src/main/java/com/duosecurity/client/Admin.java, duo-client/src/main/java/com/duosecurity/client/Auth.java, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-client/src/test/java/com/duosecurity/client/HttpRateLimitRetryTest.java, duo-example-admin/src/main/java/com/duosecurity/example/DuoAdmin.java, duo-example-admin/src/main/java/com/duosecurity/example/DuoAuthLogsV2.java, duo-example-admin/src/main/java/com/duosecurity/example/DuoIntegrations.java
Backwards compatible.  Admin will use sigVersion 5 by default
=> Create Auth, Accounts, and Admin subtypes for the client

.github/workflows/java-ci.yml, duo-client/src/main/java/com/duosecurity/client/Accounts.java, duo-client/src/main/java/com/duosecurity/client/Admin.java, duo-client/src/main/java/com/duosecurity/client/Auth.java, duo-client/src/main/java/com/duosecurity/client/Base64.java, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-client/src/main/java/com/duosecurity/client/Util.java, duo-example-admin/src/main/java/com/duosecurity/example/DuoAdmin.java, duo-example-admin/src/main/java/com/duosecurity/example/DuoAuthLogsV2.java, duo-example-admin/src/main/java/com/duosecurity/example/DuoIntegrations.java
- Try again see if ci will run
=> Add lint to ci, fix all linter issues

duo-example-admin/src/main/java/com/duosecurity/example/DuoPolicies.java
Add a bulk policy endpoint call to the policy example. Also updated references from `name` to `policy_name`. 
Policy added new bulk endpoints, and we're updating examples to show how to call them. We have also deprecated referring to the policy's name as just `name`, so the existing examples needed to be updated. 
Tested locally.
=> Add bulk policy example

.github/workflows/java-ci.yml
Update github action version to avoid node12 deprecation warnign
CI warns about node12 being deprecated 
CI should pass without any warning
=> update checkout action to v3

duo-client/pom.xml, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-example-admin/pom.xml, pom.xml
Version bump for release
This prepares the sdk for release to maven
Local build and tests pass, CI should also pass
=> Version 0.6.1 bump for release

duo-client/pom.xml, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-example-admin/pom.xml, pom.xml
Prepping for 0.6.2 release
N/A
=> Bump to 0.6.2 to prep release

README.md, duo-client/pom.xml, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-example-admin/pom.xml, pom.xml
Finish off the 0.6.2 release and begin the snapshot version of 0.6.3
N/A
=> Point README to 0.6.2 release and begin 0.6.3-SNAPSHOT

duo-client/pom.xml, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-example-admin/pom.xml, pom.xml
Typical version bump to prep release
=> Finalize the 0.6.3 version bump, removing the SNAPSHOT tag

README.md, duo-client/pom.xml, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-example-admin/pom.xml, pom.xml
Finalize the 0.6.3 release by directing people to that jar in the README.  Start the 0.6.4 SNAPSHOT
N/A
=> Finalize 0.6.3 release - update README and begin 0.6.4 SNAPSHOT

duo-client/src/main/java/com/duosecurity/client/Admin.java, duo-client/src/main/java/com/duosecurity/client/Http.java
Cutover duo_client_java fully to c5
[ZTAT-102](https://cisco-sbg.atlassian.net/browse/ZTAT-102)
N/A
=> Cutover duo_client_java fully to c5

duo-client/pom.xml, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-example-admin/pom.xml, pom.xml
Minor version bump
Tests pass and maven builds a 0.7.0 artifact
=> Version bump to 0.7.0 in preparation for release

.github/workflows/maven-deploy.yml
Use the non-deprecated version of upload-artifact
Get CI working again
CI should pass
=> Use v4 of upload-artifact

README.md, duo-client/pom.xml, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-example-admin/pom.xml, pom.xml
Refer to 0.7.0 in the README and begin the next snapshot version
=> Finalize the 0.7.0 release and begin 0.7.1-SNAPSHOT

duo-client/pom.xml, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-example-admin/pom.xml, pom.xml
=> Version bump to 0.7.1 to prep for release

README.md, duo-client/pom.xml, duo-client/src/main/java/com/duosecurity/client/Http.java, duo-example-admin/pom.xml, pom.xml
Finalize the 0.7.1 release by updating the README and starting the 0.7.2 snapshot
=> Finalize 0.7.1 and start 0.7.2 snapshot
